require "rake"
require "../common.rb"

task :default => [:unzip]

desc "download Lapack libs"
task :download do
end

task :unzip => [:download] do
end

task :install_win => [:unzip] do
  FileUtils.mkdir_p "../../lib3rd/lib"
  FileUtils.mkdir_p "../../lib3rd/dll"
  Dir['*/*.dll'].each{ |f| FileUtils.cp(f,'../../lib3rd/dll/'+File.basename(f)) }
  Dir['*/*.lib'].each{ |f| FileUtils.cp(f,'../../lib3rd/lib/'+File.basename(f)) }
end

task :clean do
end
