require "rake"
require "../common.rb"

task :default => [:unzip]

desc "download Lapack libs"
task :download do
  [
    'LAPACK_Debug_x86.zip',
    'LAPACK_Release_x86.zip',
    'LAPACK_Debug_x64.zip',
    'LAPACK_Release_x64.zip'
  ].each do |filename|
    url_download( "http://cs2.swfu.edu.cn/~zyl/lapack/#{filename}", filename )
  end
end

task :unzip => [:download] do
  [
    'LAPACK_Debug_x86.zip',
    'LAPACK_Release_x86.zip',
    'LAPACK_Debug_x64.zip',
    'LAPACK_Release_x64.zip'
  ].each do |filename|
    extract_zip( filename, 'dll' )
  end
end

task :install_win => [:unzip] do
  FileUtils.mkdir_p "../../lib3rd/lib"
  FileUtils.mkdir_p "../../lib3rd/dll"
  Dir['*/*.dll'].each{ |f| FileUtils.cp(f,'../../lib3rd/dll/'+File.basename(f)) }
  Dir['*/*.lib'].each{ |f| FileUtils.cp(f,'../../lib3rd/lib/'+File.basename(f)) }
end

task :clean do
  Dir['*/*.dll'].each{ |f| FileUtils.rm_f f }
  Dir['*/*.lib'].each{ |f| FileUtils.rm_f f }
end
