require "rake"
require "../common.rb"

task :default => [:install]

desc "install BLAS/LAPACK libs"
task :install_win do
  prefix = "../../lib3rd"
  puts "BLAS/LALACK copy files to #{prefix}"

  FileUtils.mkdir_p "#{prefix}/lib"
  FileUtils.mkdir_p "#{prefix}/dll"

  Dir['win32_debug/*.lib'].each{ |f| FileUtils.cp(f,prefix+'/lib/'+File.basename(f)) }
  Dir['win32_debug/*.dll'].each{ |f| FileUtils.cp(f,prefix+'/dll/'+File.basename(f)) }

  Dir['win32_release/*.lib'].each{ |f| FileUtils.cp(f,prefix+'/lib/'+File.basename(f)) }
  Dir['win32_release/*.dll'].each{ |f| FileUtils.cp(f,prefix+'/dll/'+File.basename(f)) }

  Dir['win64_debug/*.lib'].each{ |f| FileUtils.cp(f,prefix+'/lib/'+File.basename(f)) }
  Dir['win64_debug/*.dll'].each{ |f| FileUtils.cp(f,prefix+'/dll/'+File.basename(f)) }

  Dir['win64_release/*.lib'].each{ |f| FileUtils.cp(f,prefix+'/lib/'+File.basename(f)) }
  Dir['win64_release/*.dll'].each{ |f| FileUtils.cp(f,prefix+'/dll/'+File.basename(f)) }

end
